### ISSUE TITLE
Feature request: Floor height adjustment

### ISSUE THREAD

**Issue by BOLL7708** [Xavr0k/ChaperoneTweak#1]
Not sure if this is possible, but in the SteamVR forums over at Steam there has been many requests for a floor height adjustment which has gone unfulfilled. This app does most of the adjustments imaginable except that one :) Would be lovely to have that capability! (And to point here when someone asks for it ;))

**Comment by joycetick** [comment]
But you can modify the floor height with this software.

**Comment by BOLL7708** [comment]
Aha, I forgot to press the triggers, doh! That's what I get for not being in VR for some time xD Thanks :P Finally found it in the description too, I blame sleep deprived self.
