### ISSUE TITLE
Programm Freezes by Camera Rate Higher than 30

### ISSUE THREAD

**Issue by Gk1mtd** [Xavr0k/ChaperoneTweak#8]
Like the title says.
I enabled the camera in my vive, but with a camera refresh rate higher than 30, the programm freezes to death. With a 30 Hz everything works fine.

PS: Thank you very very much for this programm! Saved my sanity : )

**Comment by bddckr** [comment]
This sounds like a normal USB bandwidth issue. If you get issues try a different USB port or stop increasing the refresh rate. A high refresh rate or just a turned on camera can even cause tracking issues, see [this](https://support.steampowered.com/kb_article.php?ref=8566-SDZC-9326#tracking-issues) SteamVR support document.
